### ISSUE TITLE
[BUG] Player Revive mod conflict w/ Reskillable

### ISSUE THREAD

**Issue by KaleThyself** [Heaveness/Rebirth-of-the-Night-BPG-Edition--Future-Updates-#1]
**Describe the bug**

When going down into revive mode and having the skill perk "Hungry Farmer," all of your food in your inventory gets consumed by your dying body. 

**To Reproduce**  
1. Put multiple stacks of marshmallow roots into your inventory. 
2. Fall to your death or die from another untimely cause.
3. Listen. 

**Expected behavior**

I expect all of my food to not be consumed while I'm half dead. 

**Screenshots**

N/A

**Info:**
 - Modpack Version: Public Alpha 1.7

**Additional context**
My friend and I were using greater telekinesis on each other, got launched into the air, and then fell to our deaths. However, when I died with multiple stacks of marshmallow roots, my very hungry character ate every last bite with their dying breath.

**Comment by Heaveness** [comment]
That is quite hilarious but I can how that can be devastating when it happens. For the time being, I will disable that trait until my team and I decide on a replacement or a fix to that bug. Thanks for letting me know on that!

Side Note: Greater Telekinesis is always fun :)
