### ISSUE TITLE
Dismounting a Turret on a 1 block thick platform can cause the player to go fall through the platform.

### ISSUE THREAD

**Issue by iEatShadows** [Heaveness/Rebirth-of-the-Night-BPG-Edition--Future-Updates-#2]
**Describe the bug**
When mounting a Turret and then dismounting it by holding shift can cause the player to fall through 1 block floor/platform.

**To Reproduce**  

1. Place any kind of Turret on a 1 block thick floor/platform
2. Mount the Turret
3. Dismount it by HOLDING shift
4. You will fall through it.

**Expected behavior**
   - I would to expect it to dismount normally like dismounting a Horse and to not fall through 1 block thick floor/platform

**Modpack Version:**
   - Public Alpha 1.7

**Server or Singleplayer:**
   - Lan
  
**Version the world was created on:**
   - Public Alpha 1.7

**Comment by Heaveness** [comment]
If I recall this is a guy regarding with AW2's mounting system with turrets. AW2 is currently outdated on BPG's current version which will be updated in a future patch(2.1). For now, this will not be fixed until then. 

Also the Turrets and Vehicles are about roughly 3x3 in block size even if it only requires one block to place it on. For the thickness, I cannot fix it until the new update is applied. Sorry, I will re-open this bug when Update 2.1 is being worked on.
